[build]
  publish = "."
  command = "echo 'Build complete'"

# Render compatibility
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
