[build]
  publish = "."
  command = "echo 'Static HTML site - no build required'"

# Prevent any Node.js processing
[build.environment]
  SKIP_INSTALL = "true"
  NO_INSTALL = "true"
  NODE_ENV = "production"
  NPM_CONFIG_IGNORE_SCRIPTS = "true"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_OPTIONAL = "false"
  NPM_CONFIG_PRODUCTION = "false"
  CI = "false"
  NETLIFY = "true"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
