[build]
  publish = "."
  command = "echo 'Static HTML site - no build required'"

# Prevent dependency installation
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional --ignore-scripts"
  NPM_CONFIG_IGNORE_SCRIPTS = "true"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
