[build]
  publish = "."
  command = "echo 'Static HTML site - no build required'"

# Completely disable Node.js processing
[build.environment]
  SKIP_INSTALL = "true"
  NO_INSTALL = "true"
  NODE_ENV = "production"
  NPM_CONFIG_IGNORE_SCRIPTS = "true"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_OPTIONAL = "false"
  NPM_CONFIG_PRODUCTION = "false"
  CI = "false"
  NETLIFY = "true"
  # Force static site detection
  NODE_VERSION = "0"
  NPM_VERSION = "0"
  # Additional Node.js blocking
  NPM_CONFIG_SCRIPTS_PREPEND_NODE_PATH = "false"
  NPM_CONFIG_SCRIPTS_PREPEND_PREFIX = "false"
  NPM_CONFIG_SCRIPTS_PREPEND_BIN = "false"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"


