[build]
  publish = "."
  command = "echo 'Build complete'"

# Default index page
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Custom 404 page - should be last
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Language-specific 404 pages
[[redirects]]
  from = "/en/*"
  to = "/locales/en/404-en.html"
  status = 404

[[redirects]]
  from = "/ru/*"
  to = "/locales/ru/404-ru.html"
  status = 404

[[redirects]]
  from = "/fr/*"
  to = "/locales/fr/404-fr.html"
  status = 404

[[redirects]]
  from = "/ar/*"
  to = "/locales/ar/404-ar.html"
  status = 404

# Common redirects
[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/main"
  to = "/index.html"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/index.html#contact"
  status = 301

[[redirects]]
  from = "/about"
  to = "/index.html#about"
  status = 301

[[redirects]]
  from = "/packages"
  to = "/index.html#packages"
  status = 301

[[redirects]]
  from = "/payment"
  to = "/index.html#payment"
  status = 301

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
