[build]
  publish = "."

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 404 page
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"


