[build]
  publish = "."
  command = "echo 'Static HTML site - no build required'"

# Disable all Node.js processing
[build.environment]
  SKIP_INSTALL = "true"
  NO_INSTALL = "true"
  NODE_ENV = "production"
  NPM_CONFIG_IGNORE_SCRIPTS = "true"
  CI = "false"
  NETLIFY = "true"
  NODE_VERSION = "0"
  NPM_VERSION = "0"

# Redirects
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 404 page
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"


